author: Inacio Ferrarini
author_url: https://twitter.com/inacioferrarini
github_url: https://github.com/inacioferrarini/Main
root_url: https://inacioferrarini.github.io/Main/
module: Main
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'Main.xcworkspace', -scheme, 'Main-iOS']
